[green_agent]
agentbeats_id = "Jyoti-Ranjan-Das845/pi-bench"
env = {}

[[participants]]
image = "ghcr.io/ironshell-ui/lambda-security-agent:latest"
name = "agent"
env = { OPENAI_API_KEY = "${OPENAI_API_KEY}", OPENAI_API_BASE = "${OPENAI_API_BASE}", LLM_MODEL = "${LLM_MODEL}" }

[config]
domain = "policy_compliance"
num_tasks = 94
run_id = 13
